name: Build App
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build OpenBK7231N irRemoteESP
    runs-on: ubuntu-22.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v5

      - name: Version
        id: refs
        run: |
          BRANCH=${GITHUB_REF#refs/*/}
          echo "version=$(echo ${BRANCH} | tr '/' '_')_$(git rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT

      - name: Run make
        run: make APP_VERSION=${{ steps.refs.outputs.version }}_irRemoteESP APP_NAME=OpenBK7231N VARIANT="irRemoteESP" OpenBK7231N

      - name: Save build assets
        uses: actions/upload-artifact@v6
        with:
          name: OpenBK7231N_${{ steps.refs.outputs.version }}_irRemoteESP
          path: |
            output/*/OpenBK7231N*
          if-no-files-found: error
